### ISSUE TITLE
[rollkit] Error initializing BlockManager

### ISSUE THREAD

**Issue by a26nine** [ignite/apps#104]
**App**: **rollkit**

**Describe the bug**
After the recent [PR](https://github.com/ignite/apps/pull/92), the rollkit chain is unable to initialize from genesis. It throws:
```
error while initializing BlockManager: genesisValidators[0] != req.Validators[0]
Error intercepting command:  failed to run entrypoint: exit status 1
```
even when the the `genesis.json` file validator key and the local validator key are the same.

**To reproduce**
1. `ignite scaffold chain gm --address-prefix gm`
2. `cd gm`
3. `ignite app install -g github.com/ignite/apps/rollkit@rollkit/v0.2.0`
4. `ignite rollkit add`
5. `ignite chain build`
6. `ignite rollkit init`
7. `rollkit toml init`
8. `rollup start ...`

**What version are you using?**

```
Ignite CLI version:		v28.4.0
Ignite CLI build date:		2024-05-15T13:42:13Z
Ignite CLI source hash:		83ee9ba5f81f2d2104ed91808f2cb72719a23e41
Ignite CLI config version:	v1
Cosmos SDK version:		v0.50.6
Your OS:			linux
Your arch:			amd64
Your go version:		go version go1.22.4 linux/amd64
```

**Comment by julienrbrt** [comment]
Hi,

If you are using local-da for testing you need to use `--local-da` when using `rollkit init`.

Namely `ignite rollkit init --local-da`

**Comment by a26nine** [comment]
> Hi,
> 
> If you are using local-da for testing you need to use `--local-da` when using `rollkit init`.
> 
> Namely `ignite rollkit init --local-da`

I am not using local-da. It happens while using Celestia DA.

The issue is reproducible by one of the Rollkit team members:
<img width="753" alt="image" src="https://github.com/ignite/apps/assets/103454930/6cd35962-4182-4a19-86e3-bf2aa8eeee59">

**Comment by julienrbrt** [comment]
Ok, let me check 👍

**Comment by gupadhyaya** [comment]
@julienrbrt i have seen this error happen when the power requirement is different (https://github.com/ignite/apps/blob/main/rollkit/cmd/init.go#L92). For example, changing the Power to 1 was required on some integrations. May be we can flag this for user to pass custom power?

**Comment by a26nine** [comment]
> @julienrbrt i have seen this error happen when the power requirement is different (https://github.com/ignite/apps/blob/main/rollkit/cmd/init.go#L92). For example, changing the Power to 1 was required on some integrations. May be we can flag this for user to pass custom power?

I can confirm that changing the `power` to `1` resolved the issue. Thanks, @gupadhyaya!

**Comment by julienrbrt** [comment]
Looks like to me that the issue is the difference between bonded token and val power. If we make those match, the number doesn't change.

Opened https://github.com/ignite/apps/pull/106. Tried with local-da and testnet and it works.
Would be nice if one of you could confirm too :)
