### ISSUE TITLE
PROP: Enable Extension to Extend Flag in Ignite Command Using Hook

### ISSUE THREAD

**Issue by Pantani** [ignite/apps#118]

**Comment by julienrbrt** [comment]
I am not sure if this is very useful. What is the use case?

**Comment by julienrbrt** [comment]
Alright, but how will an app use that?

**Comment by Pantani** [comment]
for instance, if you want to add a flag to the chain build command to run tests after the build:

```go
func (app) Manifest(context.Context) (*plugin.Manifest, error) {
	return &plugin.Manifest{
		Name: "hooks",
		Hooks: []*plugin.Hook{
			{
				Name:        "chain-build",
				PlaceHookOn: "ignite chain build",
				Flags: []*plugin.Flag{
					{
						Name:         "run-test",
						Usage:        "Run tests after build",
						DefaultValue: "false",
						Type:         plugin.FlagTypeString,
					},
				},
			},
		},
		Commands: cmd.GetCommands(),
	}, nil
}

func (app) ExecuteHookCleanUp(_ context.Context, hook *plugin.ExecutedHook, _ plugin.ClientAPI) error {
	var (
		flags = hook.Hook.Flags
		runTests = flags.GetString("run-test")
	)

	if runTests != "" {
		tests.Run()
	}
	return nil
}
```

**Comment by julienrbrt** [comment]
Like that, I get it better now. Is it, however, really something we want to allow?
I really like that hooks are just logic running before/after/always-after regardless of the flags.
This adds granularity, sure, but imho worsen a bit the UX.

Do we actually already need this feature for something?

**Comment by julienrbrt** [comment]
Discussed on Slack. I get it and it makes sense to add the feature.
