### ISSUE TITLE
bug: gex integration tests

### ISSUE THREAD

**Issue by Pantani** [ignite/apps#27]
The integration test fails [here](https://github.com/ignite/apps/blob/86736bdc77202e58d00ddc432e9cc8025b019a59/integration/explorer/gex_test.go#L18-L18) because the `envtest.New(t)` can only be used inside the ignite project. The [method builds a new ignite binary](https://github.com/ignite/cli/blob/cb556cf3bcb1f71bb88aab5b8b43e6a057048d27/integration/env.go#L69-L69) using the current folder (`wd, err := os.Getwd()`). Every time the test tries to find the Ignite binaries in the path `$GOPATH/src/github.com/ignite/apps/integration/explorer` and does not find, causing panic in the test

**Comment by Ehsan-saradar** [comment]
@Pantani I had a [PR for cli repo](https://github.com/ignite/cli/pull/3666) that fixed this issue but it's not tagged as version so can not be used in apps go module.
