### ISSUE TITLE
FIX: Error Trying to Connect Two Chains Using Hermes

### ISSUE THREAD

**Issue by mondainai247** [ignite/apps#37]
ignite relayer hermes configure "earth" "http://localhost:26657" "http://localhost:9090" "mars" "http://localhost:26659" "http://localhost:9092"

![Screen Shot 2024-01-09 at 9 14 30 AM](https://github.com/ignite/apps/assets/60919552/aa5af8ab-e602-460d-b750-d4a8763ffb0d)
Here are the contents of the mars config.yml
![Screen Shot 2024-01-09 at 9 13 42 AM](https://github.com/ignite/apps/assets/60919552/df002511-cd30-4076-83ea-3176f2b945f9)

**Comment by Pantani** [comment]
closing because the tutorial was outdate

https://github.com/ignite/cli/pull/4214
