### ISSUE TITLE
feat(bounty): cosmwasm plugin

### ISSUE THREAD

**Issue by Pantani** [ignite/apps#56]
## A Description of the Bounty

Create a plugin to help CosmWasm developers. The plugin can be any handy tool to advance CosmWasm development, such as a plugin to scaffold smart contract templates, test, build, and publish smart contracts, or add CosmWasm support to an app scaffolded with Ignite CLI. Anything that helps the ecosystem is valid.

### Conditions to Win the Bounty

Your plugin must be related to CosmWasm. All helpful ideas are welcome. We will vote on the best idea and code. Anyone can take part in the bounty not only one specific developer.

### How to Apply for the Bounty

The plugin should be created in a new repository and the winners will be transferred to the Ignite organization. All bounties should be submitted by this GitHub issue.

#### Total Reward for the Bounty

There will be two winners with different prizes:

- 1st winner: $5,000 USD in ATOM
- 2nd winner: $2,000 USD in ATOM

#### Duration of the Bounty Program

- One month

#### Deadline for Submissions

- 21 August

#### Deadline for Results

- 1 September

**Comment by 0xankit** [comment]
is is still active?

**Comment by Pantani** [comment]
@TouchstoneTheDev and @0xankit, thanks for asking, but the bounty is inactive. We will have more cool bounties soon
