### ISSUE TITLE
Language agnostic plugins

### ISSUE THREAD

**Issue by tbruyelle** [ignite/apps#58]
Currently, a plugin must be written in go. Since the plugin system is based on a client-server stack, we can make it language agnostic.

To do that we need 2 changes in the plugin system:

1) change the network encoding: currently it's gob, which is only known by the go language. We have to switch to GRPC (I mentionned JSONRpc but I was wrong), as it is supported by the plugin library (see https://github.com/hashicorp/go-plugin/tree/master/examples/grpc)

2) find a way to describe how a plugin should be compiled and/or run. Currently the plugin system assumes the plugin is written in go, so it builds it using `go build` and then run the binary. We might need a manifest file that describes how to deal with a plugin written in an other language. If no manifest is found, we assume the plugin is written in go.

**Comment by jeronimoalbi** [comment]
Apps support gRPC since ignite/cli#3529 so the CLI is able to interact with plugins written in other languages. The next step is to support launching plugins written in other languages because right now they are expected to be written in Go. I'm creating a new issue for it.
