### ISSUE TITLE
Add consumer app metadata

### ISSUE THREAD

**Issue by Pantani** [ignite/apps#70]

**Comment by julienrbrt** [comment]
What's the context on this?

**Comment by Pantani** [comment]
add the consumer app info into the  https://github.com/ignite/apps/blob/main/app.ignite.yml file

**Comment by julienrbrt** [comment]
Oh, I think we can close then, given that file will be removed in favor or parsing the app registry

**Comment by julienrbrt** [comment]
Superseeded by https://github.com/ignite/apps/issues/94
