### ISSUE TITLE
find way to debug ignite apps commands

### ISSUE THREAD

**Issue by Pantani** [ignite/apps#76]
We should add the subcommands. But I'm checking now, and it is not working; the conversion for the Cobra commands only passes the info, not the handler. And the commands show as additional info. We should find a better way to do it

_Originally posted by @Pantani in https://github.com/ignite/apps/pull/75#discussion_r1530476762_

**Comment by julienrbrt** [comment]
For this we have integration tests. This is being deleted here: https://github.com/ignite/apps/pull/113
