### ISSUE TITLE
Refine App Registry Structure & Schema

### ISSUE THREAD

**Issue by salmad3** [ignite/apps#86]
### Context:

As we iterate on the registry's initial version, we aim to refine the structure and organization of the app schema files to enhance maintainability and usability.

Follows https://github.com/ignite/apps/pull/65 and @jeronimoalbi's [suggestion](https://github.com/ignite/apps/pull/65#issuecomment-2009223182) in particular.

### Acceptance Criteria:

- [x] **Directory Structure**: Avoid using separate folders for each app schema unless necessary for additional content like images or documents. Propose storing all schemas at the same level within a renamed directory, enhancing file management and access.
- [x] **File Naming and Formats**: Standardize the naming of schema files using a format such as `foo_name.app.json`. Consider the flexibility of supporting both JSON and YAML formats to accommodate different developer preferences.
- [x] **Registry and Schema Files**: Transition from `schema.app.json` to `registry.json` to clarify its role as the main registry file, with individual app schemas using the `.app.json` suffix. Additionally, define a straightforward JSON schema (`schema.json`) to validate the app schemas.
- [x] **Folder Naming**: Rename `_ignite-app-registry` to `registry`, simplifying the URL to `https://github.com/ignite/apps/registry` and improving semantic clarity.
- [x] **Schema Simplicity and Evolution**: Maintain a simple schema initially, incorporating only necessary features. Expand the schema dynamically based on real-world use and developer feedback.

### Notes:

- Look to established standards like `package.json` and `pyproject.toml` for best practices in schema design.
- For defining the schema validation, refer to the [JSON Schema official documentation](https://json-schema.org/).

**Comment by jeronimoalbi** [comment]
If it helps, here's a [schema.json](https://github.com/ignite/apps/files/15059707/schema.json) and an example [foo.app.json](https://github.com/ignite/apps/files/15059711/foo.app.json) App schema to test it using for example https://www.jsonschemavalidator.net. Maybe it helps as an starting point for the final JSON schema.
It was defined at some point during app registry discussions so it might be a bit outdated.

**Comment by julienrbrt** [comment]
Closed by https://github.com/ignite/apps/pull/95
