### ISSUE TITLE
Add Existing Apps to the Updated App Registry

### ISSUE THREAD

**Issue by salmad3** [ignite/apps#87]
### Context

We need to add all existing Ignite apps to the newly refined registry structure. This will make it easier for users and developers to find and utilize these apps.

### Acceptance Criteria:

- [x] **Identify Existing Apps**: Compile a list of all current apps, such as `consumer`, `explorer`, `hermes`, `marketplace`, and `wasm`.
- [x] **Create App Entries**: For each app, create an entry in the `./registry` directory using the standardizeed format.
- [ ] **Documentation**: Ensure each app entry includes a `app.json` file with relevant details such as description, dependencies, authors, and links as per the new schema requirements.

### Notes:

**Depends on https://github.com/ignite/apps/issues/86**

**Comment by julienrbrt** [comment]
Our marketplace app should be updated to use this as well instead of searching for a github tag
