### ISSUE TITLE
Create a Ledger App

### ISSUE THREAD

**Issue by fadeev** [ignite/apps#96]
Perhaps, in `config.yml` we can have:

```yaml
build:
  ledger: false # with a default value of `true`
```

https://github.com/cosmos/gaia/blob/09f9d8d65b153d1912e8d2a2fecc20aac8e905f4/Makefile#L27-L49

**Comment by julienrbrt** [comment]
A ledger app does not really make sense. This issue was about ledger support in chain build, and ignite already support custom build tags.
